#!/bin/env python3
# author: Samie B.
# date: 2022-02-16 Wednesday
# Returns today's date in my own 3-char format

import time
import sys

if len(sys.argv) > 1:
  T = time.localtime(time.time() + 24*3600 * int(sys.argv[1]))
else:
  T = time.localtime()

Y = T.tm_year % 10
M = "JFMAYULGSOND"[T.tm_mon-1]
D = "1234567890QWERTYUIOXASDFGHJKLCZ"[T.tm_mday-1]

#if len(sys.argv) > 1:
Y = "ZOTEFISVHN"[Y]

print(str(Y)+M+D)
