mobile:
	gcc -o program -Iraylib/raylib/src source.c -flto -lraylib -Lraylib/raylib/src  -lm -ldl -lpthread -lX11 -lxcb -lGL -lGLX -lXext -lGLdispatch -lXau -lXdmcp

desktop:
	gcc -o program source.c -lraylib -flto -lm -ldl -lpthread -lX11 -lxcb -lGL -lGLX -lXext -lGLdispatch -lXau -lXdmcp

